module.exports = {
  SERVER_PORT: process.env.SERVER_PORT,
  SHOPIFY_WEBHOOK_VERIFICATION_KEY: process.env.SHOPIFY_WEBHOOK_VERIFICATION_KEY,
  SHOPIFY_WEBHOOK_API_VERIFICATION_KEY: process.env.SHOPIFY_WEBHOOK_API_VERIFICATION_KEY
};
